name: "Build & Push"
inputs:
  SERVER_MESSAGE:
  tag:
  docker_username:
  docker_access_token:
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_access_token }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5.0.0
      with:
        build-args: SERVER_MESSAGE=${{ inputs.SERVER_MESSAGE }}
        file: Dockerfile
        push: true
        tags: ${{ inputs.tag }}
