name: Build workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ inputs.environment }}:latest
          file: Dockerfile
          build-args: |
            SERVER_MESSAGE=${{ secrets.SERVER_MESSAGE }}
