name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

deploy:
  runs-on: ubuntu-latest
  environment: ${{ inputs.environment }}
  needs: review
  steps:
    - uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 4001
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker run -d --name dehancer-cicd-testing -p 1234:8080 ghcr.io/${{ github.repository }}-${{ inputs.environment }}:latest