name: Staging

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build_staging:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          file: Dockerfile
          build-args: |
            APP_ENV="staging"
            FBQ=${{ secrets.FBQ }}
            GTM=${{ secrets.GTM }}
            GTAG=${{ secrets.GTAG }}
            GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }}
            PADDLE_VENDOR_ID=${{ secrets.PADDLE_VENDOR_ID }}
            PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}
            CLOUDPAYMENTS_PUBLIC_ID=${{ secrets.CLOUDPAYMENTS_PUBLIC_ID }}
  deploy_staging:
    runs-on: ubuntu-latest
    needs: build_staging
    environment: staging
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ${{ secrets.SSH_URL }} "docker run -d -p 1234:8080 ghcr.io/${{ github.repository }}:latest"
