name: Testing Github Actions
run-name: ${{ github.actor }} is testing out Github Actions

on:
  push:
  workflow_dispatch:

jobs:
  build_production:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout 123"
        uses: actions/checkout@v4.0.0
      - uses: .github/actions/build-push
        with:
          SERVER_MESSAGE: ${{ secrets.SERVER_MESSAGE }}
          tag: ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest
  deploy_production:
    runs-on: ubuntu-latest
    needs: [build_production]
    steps:
      - name: Run on remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ${{ secrets.SSH_URL }} "docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest"
