name: Workflow

on:
  push:
    branches: master
      develop
      'feature/**'
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build_production:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      environment: production
    secrets: inherit
  review_production:
    needs: build_production
    uses: ./.github/workflows/review.yml
  deploy_production:
    needs: review_production
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
