name: Testing Github Actions
run-name: ${{ github.actor }} is testing out Github Actions

on:
  push:
  workflow_dispatch:

jobs:
  build_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5.0.0
        with:
          build-args: SERVER_MESSAGE=${{ secrets.SERVER_MESSAGE }}
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest
  staging_production:
    runs-on: ubuntu-latest
    steps:
      - name: Run on remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ${{ secrets.SSH_URL }} "docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest"
