name: Full workflow

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"

jobs:
  production:
    if: github.ref_name == 'master'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable/reviewed_deployment.yml
    with:
      environment: production
    secrets: inherit

  staging:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable/standard_workflow.yml
    with:
      environment: staging
    secrets: inherit
