name: Full workflow

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"

jobs:
  production:
    name: Production
    if: github.ref_name == 'master'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      environment: production
    secrets: inherit

  staging:
    name: Staging
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/standard_workflow.yml
    with:
      environment: staging
    secrets: inherit
