name: Main workflow

on:
  workflow_dispatch:

jobs:
  main:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        environment: [production, staging]
    uses: ./.github/workflows/env-specific.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
