name: Reviewed deployment workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  review:
    needs: build
    uses: ./.github/workflows/review.yml
  deploy:
    needs: review
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
