name: Staging
run-name: ${{ github.actor }} is testing deployment to staging

on:
  push:
    branches:
      - master
      - develop

env:
  tag: ${{ secrets.DOCKER_HUB_USERNAME }}/image:latest

jobs:
  build_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: ./.github/actions/build-push
        with:
          SERVER_MESSAGE: ${{ secrets.SERVER_MESSAGE }}
          tag: ${{ env.tag }}
          docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  deploy_staging:
    runs-on: ubuntu-latest
    needs: build_staging
    environment: staging
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: ./.github/actions/deploy
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_url: ${{ secrets.SSH_URL }}
          tag: ${{ env.tag }}
