name: Test123
run-name: ${{ github.actor }} is testing deployment to test

on:
#  push:
#   branches: ["test"]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ${{ secrets.SSH_URL }} "docker run -d -p 1234:8080 ghcr.io/${{ github.repository }}:latest"
